PENDING_DETAIL_STATUS = "PENDING_DETAIL"
READY_FOR_REVIEW_STATUS = "READY_FOR_REVIEW"
APPROVED_STATUS = "APPROVED"
REJECTED_FOR_EDIT_STATUS = "REJECTED_FOR_EDIT"
REJECTED_FINAL_STATUS = "REJECTED_FINAL"
CANCELLED_STATUS = "CANCELLED"

BASE_CURRENCY_CODE = "PEN"
