PROVISION_ENTITY_TYPE = "provision"
PROVISION_DOCUMENT_ENTITY_TYPE = "provision_document"

ALLOWED_ATTACHMENT_ENTITY_TYPES = frozenset(
    {
        PROVISION_ENTITY_TYPE,
        PROVISION_DOCUMENT_ENTITY_TYPE,
    }
)
