"""update ventas

Revision ID: 163a5f154f28
Revises: 4d8e2df158db
Create Date: 2026-06-01 21:53:50.734397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163a5f154f28'
down_revision: Union[str, Sequence[str], None] = '4d8e2df158db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('vendedor', sa.String(), nullable=True), schema='coolbox')
    op.add_column('ventas', sa.Column('iva', sa.Float(), nullable=True), schema='coolbox')
    op.alter_column('ventas', 'cliente',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='coolbox')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ventas', 'cliente',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='coolbox')
    op.drop_column('ventas', 'iva', schema='coolbox')
    op.drop_column('ventas', 'vendedor', schema='coolbox')
    # ### end Alembic commands ###
