"""update tables libro mayor 3

Revision ID: 1bb3f9a3c756
Revises: da33f3ddabe7
Create Date: 2026-06-01 11:44:05.784186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb3f9a3c756'
down_revision: Union[str, Sequence[str], None] = 'da33f3ddabe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libro_mayor', sa.Column('fecha_creacion', sa.DateTime(), nullable=False), schema='finance')
    op.add_column('libro_mayor', sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False), schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libro_mayor', 'fecha_actualizacion', schema='finance')
    op.drop_column('libro_mayor', 'fecha_creacion', schema='finance')
    # ### end Alembic commands ###
