"""add model tickets

Revision ID: 21e63a34178b
Revises: ef02777e87eb
Create Date: 2026-06-13 00:47:05.990809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e63a34178b'
down_revision: Union[str, Sequence[str], None] = 'ef02777e87eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('numero_de_ticket', sa.Integer(), nullable=False),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=False),
    sa.Column('creado_por', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('sub_area_tienda', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('nombres_del_solicitante', sa.String(), nullable=True),
    sa.Column('numero_telefonico', sa.Integer(), nullable=True),
    sa.Column('medio_de_contacto', sa.String(), nullable=True),
    sa.Column('area_del_servicio', sa.String(), nullable=True),
    sa.Column('asunto', sa.String(), nullable=True),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('causa_raiz', sa.String(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('fecha_nivel_1', sa.DateTime(), nullable=False),
    sa.Column('resolucion_nivel_1', sa.String(), nullable=True),
    sa.Column('soporte_nivel_1', sa.String(), nullable=True),
    sa.Column('fecha_nivel_2', sa.DateTime(), nullable=True),
    sa.Column('resolucion_nivel_2', sa.String(), nullable=True),
    sa.Column('soporte_nivel_2', sa.String(), nullable=True),
    sa.Column('asignado_a', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['security.auth.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['security.auth.id'], ),
    sa.PrimaryKeyConstraint('numero_de_ticket')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
