"""add companie

Revision ID: 2561d257d693
Revises: 205b51acfb27
Create Date: 2026-05-23 22:18:37.188329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2561d257d693'
down_revision: Union[str, Sequence[str], None] = '205b51acfb27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['security.auth.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['security.auth.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='master'
    )
    op.add_column('provision_concepts', sa.Column('company_id', sa.Integer(), nullable=False), schema='finance')
    op.create_foreign_key(None, 'provision_concepts', 'companies', ['company_id'], ['id'], source_schema='finance', referent_schema='master')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provision_concepts', schema='finance', type_='foreignkey')
    op.drop_column('provision_concepts', 'company_id', schema='finance')
    op.drop_table('companies', schema='master')
    # ### end Alembic commands ###
