"""add catalogo

Revision ID: 4d8e2df158db
Revises: 53537c5f1fb5
Create Date: 2026-06-01 00:28:25.067629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d8e2df158db'
down_revision: Union[str, Sequence[str], None] = '53537c5f1fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('codigo_comercial', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('rubro', sa.String(), nullable=True),
    sa.Column('familia', sa.String(), nullable=True),
    sa.Column('subfamilia', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('descatalogado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='coolbox'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos', schema='coolbox')
    # ### end Alembic commands ###
