"""add tables libro mayor 2

Revision ID: 6a2995115995
Revises: e6a5ec428c67
Create Date: 2026-06-01 09:59:56.905651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a2995115995'
down_revision: Union[str, Sequence[str], None] = 'e6a5ec428c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libro_mayor',
    sa.Column('transaccion_id', sa.INTEGER(), nullable=False),
    sa.Column('linea', sa.INTEGER(), nullable=False),
    sa.Column('fecha_contabilizacion', sa.Date(), nullable=False),
    sa.Column('fecha_documento', sa.Date(), nullable=False),
    sa.Column('numero_documento', sa.String(length=50), nullable=False),
    sa.Column('transaccion_tipo', sa.String(length=50), nullable=False),
    sa.Column('folio', sa.String(length=50), nullable=True),
    sa.Column('tipo_documento', sa.String(length=50), nullable=True),
    sa.Column('cuenta_asociada', sa.String(length=50), nullable=False),
    sa.Column('nombre_cuenta_asociada', sa.String(length=100), nullable=False),
    sa.Column('proveedor', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('comentario_linea', sa.String(length=255), nullable=True),
    sa.Column('cuenta_contrapartida', sa.String(length=50), nullable=False),
    sa.Column('nombre_contrapartida', sa.String(length=100), nullable=False),
    sa.Column('referencia_1', sa.String(length=50), nullable=True),
    sa.Column('referencia_2', sa.String(length=50), nullable=True),
    sa.Column('referencia_3', sa.String(length=50), nullable=True),
    sa.Column('cargo_abono_ml', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('cargo_abono_me', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('centro_costo', sa.String(length=50), nullable=True),
    sa.Column('centro_area', sa.String(length=50), nullable=True),
    sa.Column('nombre_area', sa.String(length=100), nullable=True),
    sa.Column('id_regla', sa.INTEGER(), nullable=True),
    sa.Column('tiene_regla', sa.Boolean(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('subcodigo', sa.String(length=50), nullable=True),
    sa.Column('nombre_cuenta', sa.String(length=100), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['security.auth.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['security.auth.id'], ),
    sa.PrimaryKeyConstraint('transaccion_id', 'linea'),
    schema='finance'
    )
    op.create_table('reglas_gastos',
    sa.Column('id_regla', sa.Integer(), nullable=False),
    sa.Column('prioridad', sa.INTEGER(), nullable=False),
    sa.Column('nombre_regla', sa.String(length=150), nullable=False),
    sa.Column('tipo_regla', sa.String(length=20), nullable=False),
    sa.Column('cuenta', sa.String(length=15), nullable=True),
    sa.Column('cuenta_contrapartida', sa.String(length=15), nullable=True),
    sa.Column('centro_costo', sa.String(length=30), nullable=True),
    sa.Column('filtro_texto', sa.String(length=255), nullable=True),
    sa.Column('texto_excluido', sa.String(length=255), nullable=True),
    sa.Column('monto_min', sa.Numeric(precision=19, scale=6), nullable=True),
    sa.Column('monto_max', sa.Numeric(precision=19, scale=6), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('subcodigo', sa.String(length=50), nullable=False),
    sa.Column('nombre_cuenta', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['security.auth.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['security.auth.id'], ),
    sa.PrimaryKeyConstraint('id_regla'),
    schema='finance'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reglas_gastos', schema='finance')
    op.drop_table('libro_mayor', schema='finance')
    # ### end Alembic commands ###
