"""Descripción del cambio

Revision ID: 7da7715270af
Revises: 163a5f154f28
Create Date: 2026-06-18 00:18:41.376960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da7715270af'
down_revision: Union[str, Sequence[str], None] = '163a5f154f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_canal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_dim_canal_codigo'),
    schema='coolbox'
    )
    op.create_index('ix_dim_canal_codigo', 'dim_canal', ['codigo'], unique=False, schema='coolbox')
    op.create_table('dim_cliente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_dim_cliente_codigo'),
    schema='coolbox'
    )
    op.create_index('ix_dim_cliente_codigo', 'dim_cliente', ['codigo'], unique=False, schema='coolbox')
    op.create_table('dim_producto',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('codigo_comercial', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('rubro', sa.String(), nullable=True),
    sa.Column('familia', sa.String(), nullable=True),
    sa.Column('subfamilia', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('descatalogado', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_dim_producto_codigo'),
    schema='coolbox'
    )
    op.create_index('ix_dim_producto_codigo', 'dim_producto', ['codigo'], unique=False, schema='coolbox')
    op.create_table('dim_tienda',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('formato', sa.String(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('metraje', sa.Float(), nullable=True),
    sa.Column('ubigeo', sa.String(), nullable=True),
    sa.Column('departamento', sa.String(), nullable=True),
    sa.Column('provincia', sa.String(), nullable=True),
    sa.Column('distrito', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_dim_tienda_codigo'),
    schema='coolbox'
    )
    op.create_index('ix_dim_tienda_codigo', 'dim_tienda', ['codigo'], unique=False, schema='coolbox')
    op.create_table('stg_ventas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('documento', sa.String(), nullable=False),
    sa.Column('tipo_documento', sa.String(), nullable=False),
    sa.Column('tienda_codigo', sa.String(), nullable=False),
    sa.Column('producto_codigo', sa.String(), nullable=False),
    sa.Column('canal_codigo', sa.String(), nullable=False),
    sa.Column('cliente_codigo', sa.String(), nullable=True),
    sa.Column('vendedor_codigo', sa.String(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('descuento', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('iva', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='coolbox'
    )
    op.create_index('ix_stg_ventas_documento', 'stg_ventas', ['documento'], unique=False, schema='coolbox')
    op.create_index('ix_stg_ventas_fecha', 'stg_ventas', ['fecha'], unique=False, schema='coolbox')
    op.create_table('fact_ventas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('documento', sa.String(), nullable=False),
    sa.Column('tipo_documento', sa.String(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('canal_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('descuento', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('iva', sa.Float(), nullable=True),
    sa.Column('vendedor_codigo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canal_id'], ['coolbox.dim_canal.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['coolbox.dim_cliente.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['coolbox.dim_producto.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['coolbox.dim_tienda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha', 'documento', 'producto_id', 'precio', name='uq_fact_venta_linea'),
    schema='coolbox'
    )
    op.create_index('ix_fact_ventas_canal_id', 'fact_ventas', ['canal_id'], unique=False, schema='coolbox')
    op.create_index('ix_fact_ventas_cliente_id', 'fact_ventas', ['cliente_id'], unique=False, schema='coolbox')
    op.create_index('ix_fact_ventas_documento', 'fact_ventas', ['documento'], unique=False, schema='coolbox')
    op.create_index('ix_fact_ventas_fecha', 'fact_ventas', ['fecha'], unique=False, schema='coolbox')
    op.create_index('ix_fact_ventas_producto_id', 'fact_ventas', ['producto_id'], unique=False, schema='coolbox')
    op.create_index('ix_fact_ventas_tienda_id', 'fact_ventas', ['tienda_id'], unique=False, schema='coolbox')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fact_ventas_tienda_id', table_name='fact_ventas', schema='coolbox')
    op.drop_index('ix_fact_ventas_producto_id', table_name='fact_ventas', schema='coolbox')
    op.drop_index('ix_fact_ventas_fecha', table_name='fact_ventas', schema='coolbox')
    op.drop_index('ix_fact_ventas_documento', table_name='fact_ventas', schema='coolbox')
    op.drop_index('ix_fact_ventas_cliente_id', table_name='fact_ventas', schema='coolbox')
    op.drop_index('ix_fact_ventas_canal_id', table_name='fact_ventas', schema='coolbox')
    op.drop_table('fact_ventas', schema='coolbox')
    op.drop_index('ix_stg_ventas_fecha', table_name='stg_ventas', schema='coolbox')
    op.drop_index('ix_stg_ventas_documento', table_name='stg_ventas', schema='coolbox')
    op.drop_table('stg_ventas', schema='coolbox')
    op.drop_index('ix_dim_tienda_codigo', table_name='dim_tienda', schema='coolbox')
    op.drop_table('dim_tienda', schema='coolbox')
    op.drop_index('ix_dim_producto_codigo', table_name='dim_producto', schema='coolbox')
    op.drop_table('dim_producto', schema='coolbox')
    op.drop_index('ix_dim_cliente_codigo', table_name='dim_cliente', schema='coolbox')
    op.drop_table('dim_cliente', schema='coolbox')
    op.drop_index('ix_dim_canal_codigo', table_name='dim_canal', schema='coolbox')
    op.drop_table('dim_canal', schema='coolbox')
    # ### end Alembic commands ###
