"""update tables libro mayor

Revision ID: 82b2920aa046
Revises: d52c14bb77d2
Create Date: 2026-06-01 11:38:31.418639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b2920aa046'
down_revision: Union[str, Sequence[str], None] = 'd52c14bb77d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('libro_mayor', 'referencia_1',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True,
               schema='finance')
    op.alter_column('libro_mayor', 'referencia_2',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True,
               schema='finance')
    op.alter_column('libro_mayor', 'referencia_3',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True,
               schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('libro_mayor', 'referencia_3',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               schema='finance')
    op.alter_column('libro_mayor', 'referencia_2',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               schema='finance')
    op.alter_column('libro_mayor', 'referencia_1',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               schema='finance')
    # ### end Alembic commands ###
