"""update tables libro mayor 6

Revision ID: 9a6f0a1eee8a
Revises: cc6e68cb1a91
Create Date: 2026-06-01 12:28:56.829992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6f0a1eee8a'
down_revision: Union[str, Sequence[str], None] = 'cc6e68cb1a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('libro_mayor', 'cuenta_asociada',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False,
               schema='finance')
    op.alter_column('libro_mayor', 'proveedor',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='finance')
    op.alter_column('libro_mayor', 'cuenta_contrapartida',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True,
               schema='finance')
    op.alter_column('libro_mayor', 'nombre_contrapartida',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=True,
               schema='finance')
    op.alter_column('libro_mayor', 'centro_costo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True,
               schema='finance')
    op.alter_column('libro_mayor', 'centro_area',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True,
               schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('libro_mayor', 'centro_area',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               schema='finance')
    op.alter_column('libro_mayor', 'centro_costo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               schema='finance')
    op.alter_column('libro_mayor', 'nombre_contrapartida',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               nullable=False,
               schema='finance')
    op.alter_column('libro_mayor', 'cuenta_contrapartida',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False,
               schema='finance')
    op.alter_column('libro_mayor', 'proveedor',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               schema='finance')
    op.alter_column('libro_mayor', 'cuenta_asociada',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='finance')
    # ### end Alembic commands ###
