"""update tables libro mayor 4

Revision ID: af6c3c2bc1f4
Revises: 1bb3f9a3c756
Create Date: 2026-06-01 12:01:18.677191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6c3c2bc1f4'
down_revision: Union[str, Sequence[str], None] = '1bb3f9a3c756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reglas_gastos', 'nombre_regla', schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reglas_gastos', sa.Column('nombre_regla', sa.VARCHAR(length=150), autoincrement=False, nullable=False), schema='finance')
    # ### end Alembic commands ###
