"""update tables libro mayor 5

Revision ID: cc6e68cb1a91
Revises: af6c3c2bc1f4
Create Date: 2026-06-01 12:20:09.665164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc6e68cb1a91'
down_revision: Union[str, Sequence[str], None] = 'af6c3c2bc1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('libro_mayor', 'transaccion_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('libro_mayor', 'transaccion_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='finance')
    # ### end Alembic commands ###
