"""add tables libro mayor constain

Revision ID: ced91a28c720
Revises: 6a2995115995
Create Date: 2026-06-01 10:16:19.758343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced91a28c720'
down_revision: Union[str, Sequence[str], None] = '6a2995115995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'libro_mayor', ['transaccion_id', 'linea'], schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'libro_mayor', schema='finance', type_='unique')
    # ### end Alembic commands ###
