"""add tables libro mayor 3

Revision ID: d52c14bb77d2
Revises: ced91a28c720
Create Date: 2026-06-01 11:30:48.965138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd52c14bb77d2'
down_revision: Union[str, Sequence[str], None] = 'ced91a28c720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libro_mayor', sa.Column('fecha_creacion', sa.DateTime(), nullable=False), schema='finance')
    op.add_column('libro_mayor', sa.Column('fecha_sincronizacion', sa.DateTime(), nullable=False), schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libro_mayor', 'fecha_sincronizacion', schema='finance')
    op.drop_column('libro_mayor', 'fecha_creacion', schema='finance')
    # ### end Alembic commands ###
