"""update tables libro mayor 2

Revision ID: da33f3ddabe7
Revises: 82b2920aa046
Create Date: 2026-06-01 11:42:57.093404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da33f3ddabe7'
down_revision: Union[str, Sequence[str], None] = '82b2920aa046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libro_mayor', 'fecha_actualizacion', schema='finance')
    op.drop_column('libro_mayor', 'fecha_sincronizacion', schema='finance')
    op.drop_column('libro_mayor', 'fecha_creacion', schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libro_mayor', sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False), schema='finance')
    op.add_column('libro_mayor', sa.Column('fecha_sincronizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False), schema='finance')
    op.add_column('libro_mayor', sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False), schema='finance')
    # ### end Alembic commands ###
