"""add audit update 2

Revision ID: df29310ab5c3
Revises: 378226f68a90
Create Date: 2026-05-08 15:55:38.307112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df29310ab5c3'
down_revision: Union[str, Sequence[str], None] = '378226f68a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'endpoint_name', schema='audit')
    op.drop_column('logs', 'service_name', schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('service_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='audit')
    op.add_column('logs', sa.Column('endpoint_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema='audit')
    # ### end Alembic commands ###
