"""add tables libro mayor

Revision ID: e6a5ec428c67
Revises: f94eaeda6c5e
Create Date: 2026-06-01 09:56:06.677030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a5ec428c67'
down_revision: Union[str, Sequence[str], None] = 'f94eaeda6c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provisions', sa.Column('description', sa.String(length=255), nullable=True), schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provisions', 'description', schema='finance')
    # ### end Alembic commands ###
