"""Descripción del cambio

Revision ID: ef02777e87eb
Revises: 9a6f0a1eee8a
Create Date: 2026-06-09 22:04:13.430354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef02777e87eb'
down_revision: Union[str, Sequence[str], None] = '9a6f0a1eee8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libro_mayor', sa.Column('tipo_cuenta', sa.String(length=50), nullable=True), schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libro_mayor', 'tipo_cuenta', schema='finance')
    # ### end Alembic commands ###
