from enum import StrEnum


class JobType(StrEnum):
    SAP_DOCUMENT_ACTION = "SAP_DOCUMENT_ACTION"
    SAP_RECONCILIATION = "SAP_RECONCILIATION"
    PAYMENT_PROVIDER_EMAIL = "PAYMENT_PROVIDER_EMAIL"


class JobStatus(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    DISPATCH_FAILED = "DISPATCH_FAILED"
    RUNNING = "RUNNING"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_ERRORS = "COMPLETED_WITH_ERRORS"
    FAILED = "FAILED"


class JobBatchStatus(StrEnum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    RETRYING = "RETRYING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_ERRORS = "COMPLETED_WITH_ERRORS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class JobItemStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


TERMINAL_JOB_STATUSES = {
    JobStatus.CANCELLED,
    JobStatus.COMPLETED,
    JobStatus.COMPLETED_WITH_ERRORS,
    JobStatus.FAILED,
}

TERMINAL_BATCH_STATUSES = {
    JobBatchStatus.COMPLETED,
    JobBatchStatus.COMPLETED_WITH_ERRORS,
    JobBatchStatus.FAILED,
    JobBatchStatus.CANCELLED,
}

JOBS_VIEW_PERMISSION = "jobs.view"
JOBS_VIEW_ALL_PERMISSION = "jobs.view_all"
JOBS_CANCEL_PERMISSION = "jobs.cancel"
JOBS_CANCEL_ALL_PERMISSION = "jobs.cancel_all"
JOBS_RETRY_PERMISSION = "jobs.retry"
